---
- name: install mongodb gpg key
  apt_key: keyserver="keyserver.ubuntu.com" id=7F0CEB10 state=present

- name: add mongodb deb repository
  apt_repository: repo='deb http://downloads-distro.mongodb.org/repo/debian-sysvinit dist 10gen' state=present

- name: enforce locales
  command: "{{ item }}"
  with_items:
      - sudo update-locale LANGUAGE=C LC_ALL=C LANG=C
      - sudo locale-gen

- name: install mongodb packages
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
    force: yes
  vars:
    packages:
      - mongodb-org
  notify: restart mongodb
